server:
  port: 8001

spring:
  # 对应 RedisProperties 类
  redis:
    host: redis.kimzing.com
    port: 6379
    # Redis 服务器密码，默认为空。生产中，一定要设置 Redis 密码！
    #password:
    # Redis 数据库号，默认为 0
    database: 0
    # Redis 连接超时时间，单位：毫秒
    timeout: 1000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 添加&allowMultiQueries=true使得一个接口可以执行多条语句
    url: jdbc:mysql://mysql.kimzing.com:3306/springcloud-user?setUnicode=true&characterEncoding=utf8&allowMultiQueries=true&queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=mysql-${spring.application.name}
    username: root
    password: 123456

dubbo:
  cloud:
    # 服务消费方订阅服务提供方的应用名称的列表
    # 若需订阅多应用，使用 "," 分割
    subscribed-services: service-order
  scan:
    # dubbo 服务扫描基础包路径
    base-packages: com.kimzing.template.service